package com.armanware.wifivision
import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.graphics.Color
import android.hardware.*
import android.net.wifi.ScanResult
import android.net.wifi.WifiManager
import android.os.*
import android.view.*
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import androidx.camera.core.*
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.core.content.ContextCompat
import com.google.ar.core.*

class MainActivity:AppCompatActivity(),SensorEventListener{
 private lateinit var previewView:PreviewView;private lateinit var overlay:WifiOverlayView;private lateinit var networkText:TextView;private lateinit var modeText:TextView;private lateinit var locatePanel:View;private lateinit var locateStatus:TextView;private lateinit var directionArrow:TextView;private lateinit var locateTitle:TextView;private lateinit var apPanel:View;private lateinit var apListContainer:LinearLayout;private lateinit var scanStatus:TextView;private lateinit var wifiManager:WifiManager;private lateinit var sensorManager:SensorManager
 private var stepSensor:Sensor?=null;private var rotationSensor:Sensor?=null;private var stepBase=-1;private var stepCount=0;private var azimuth=0f;private var arSession:Session?=null;private var arReady=false;private var arOriginX=0f;private var arOriginZ=0f;private var arOriginSet=false
 private val handler=Handler(Looper.getMainLooper());private var surveying=false;private var locating=false;private var bestRssi=-100;private var previousRssi=-100;private var targetBssid:String?=null;private var targetSsid:String?=null;private var targetRssi:Int?=null
 private val permissionLauncher=registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){startIfReady()};private val poller=object:Runnable{override fun run(){updateWifi();if(targetBssid!=null&&(surveying||locating))refreshScanResults(false);if(apPanel.visibility==View.VISIBLE)refreshScanResults(false);handler.postDelayed(this,700)}}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);previewView=findViewById(R.id.previewView);overlay=findViewById(R.id.wifiOverlay);networkText=findViewById(R.id.networkText);modeText=findViewById(R.id.modeText);locatePanel=findViewById(R.id.locatePanel);locateStatus=findViewById(R.id.locateStatus);directionArrow=findViewById(R.id.directionArrow);locateTitle=findViewById(R.id.locateTitle);apPanel=findViewById(R.id.apPanel);apListContainer=findViewById(R.id.apListContainer);scanStatus=findViewById(R.id.scanStatus);wifiManager=applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager;sensorManager=getSystemService(Context.SENSOR_SERVICE) as SensorManager;stepSensor=sensorManager.getDefaultSensor(Sensor.TYPE_STEP_COUNTER);rotationSensor=sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR)
 findViewById<Button>(R.id.cameraButton).setOnClickListener{overlay.mode=WifiOverlayView.Mode.AR;modeText.text="AR CAMERA • LIVE SIGNAL FIELD"};findViewById<Button>(R.id.heatmapButton).setOnClickListener{overlay.mode=WifiOverlayView.Mode.HEATMAP;modeText.text="HEATMAP • LIVE RSSI MAP"};findViewById<Button>(R.id.propagationButton).setOnClickListener{overlay.mode=WifiOverlayView.Mode.PROPAGATION;modeText.text="RF MAP • ${overlay.surveyCount()} SPATIAL SAMPLES"}
 findViewById<Button>(R.id.surveyButton).setOnClickListener{surveying=!surveying;if(surveying){overlay.clearSurvey();arOriginSet=false;stepBase=-1;initAr();modeText.text="● AR SURVEY • MOVE CAMERA SLOWLY"}else modeText.text="SURVEY SAVED • RF VIEW (${overlay.surveyCount()} samples)"};findViewById<Button>(R.id.locateButton).setOnClickListener{targetBssid=null;targetSsid=null;startLocator("Connected Wi-Fi")};findViewById<Button>(R.id.closeLocateButton).setOnClickListener{locating=false;locatePanel.visibility=View.GONE};findViewById<Button>(R.id.apListButton).setOnClickListener{apPanel.visibility=View.VISIBLE;requestScan()};findViewById<Button>(R.id.scanButton).setOnClickListener{requestScan()};findViewById<Button>(R.id.closeApButton).setOnClickListener{apPanel.visibility=View.GONE};requestPermissionsNow()}
 private fun requestPermissionsNow(){val p=mutableListOf(Manifest.permission.CAMERA,Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACTIVITY_RECOGNITION);if(Build.VERSION.SDK_INT>=33)p+=Manifest.permission.NEARBY_WIFI_DEVICES;permissionLauncher.launch(p.toTypedArray())}
 private fun startIfReady(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)startCamera();handler.removeCallbacks(poller);handler.post(poller)}
 private fun startCamera(){val f=ProcessCameraProvider.getInstance(this);f.addListener({val p=f.get();val pr=Preview.Builder().build().also{it.setSurfaceProvider(previewView.surfaceProvider)};p.unbindAll();p.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,pr)},ContextCompat.getMainExecutor(this))}
 private fun initAr(){try{if(arSession==null)arSession=Session(this);arSession?.configure(Config(arSession).apply{updateMode=Config.UpdateMode.LATEST_CAMERA_IMAGE});arSession?.resume();arReady=true;modeText.text="● AR SURVEY • TRACKING STARTED"}catch(e:Exception){arReady=false;modeText.text="● SURVEY • SENSOR FALLBACK"}}
 @Suppress("DEPRECATION") private fun requestScan(){try{scanStatus.text=if(wifiManager.startScan())"Scanning nearby APs…" else "Android scan throttled — latest scan";handler.postDelayed({refreshScanResults(true)},1400)}catch(_:SecurityException){scanStatus.text="Wi-Fi permission required"}}
 @Suppress("DEPRECATION") private fun refreshScanResults(force:Boolean){try{val r=wifiManager.scanResults.sortedByDescending{it.level}.distinctBy{it.BSSID};if(force||apListContainer.childCount==0)renderAps(r);targetBssid?.let{b->r.firstOrNull{it.BSSID.equals(b,true)}?.let{targetRssi=it.level;if(locating)updateLocator(it.level)}}}catch(_:SecurityException){}}
 private fun renderAps(rs:List<ScanResult>){apListContainer.removeAllViews();scanStatus.text="${rs.size} radios found • tap one to select";rs.take(40).forEach{ap->val ssid=if(Build.VERSION.SDK_INT>=33)ap.wifiSsid?.toString()?.trim('"')?.ifBlank{"Hidden network"}?:"Hidden network" else @Suppress("DEPRECATION") ap.SSID.ifBlank{"Hidden network"};val b=Button(this).apply{isAllCaps=false;textAlignment=View.TEXT_ALIGNMENT_TEXT_START;text="$ssid\n${ap.level} dBm • ${band(ap.frequency)} CH ${channel(ap.frequency)}\n${ap.BSSID}";setTextColor(Color.WHITE);setBackgroundColor(Color.rgb(16,38,58));setOnClickListener{targetBssid=ap.BSSID;targetSsid=ssid;targetRssi=ap.level;apPanel.visibility=View.GONE;startLocator("$ssid • ${ap.BSSID}")}};apListContainer.addView(b)}}
 private fun band(f:Int)=when{f>=5925->"6 GHz";f>=4900->"5 GHz";else->"2.4 GHz"};private fun channel(f:Int)=when{f==2484->14;f in 2412..2472->(f-2407)/5;f in 5000..5895->(f-5000)/5;f>=5955->(f-5950)/5;else->0}
 private fun startLocator(n:String){locating=true;bestRssi=-100;previousRssi=-100;locateTitle.text="RF LOCATOR • $n";locatePanel.visibility=View.VISIBLE;locateStatus.text="Move several feet and rotate slowly"}
 @Suppress("DEPRECATION") private fun updateWifi(){try{val info=wifiManager.connectionInfo;val r=targetRssi?:info.rssi;overlay.setRssi(r,surveying);if(surveying)recordSpatial(r);if(targetBssid==null&&locating)updateLocator(info.rssi);val ssid=targetSsid?:info.ssid?.trim('"')?:"Unknown";networkText.text="$ssid   $r dBm"+(if(surveying)" • ${overlay.surveyCount()} spatial points" else "")}catch(_:SecurityException){}}
 private fun recordSpatial(r:Int){if(arReady){try{val frame=arSession?.update();val cam=frame?.camera;if(cam!=null&&cam.trackingState==TrackingState.TRACKING){val p=cam.pose;if(!arOriginSet){arOriginX=p.tx();arOriginZ=p.tz();arOriginSet=true};overlay.addSpatialSample(r,p.tx()-arOriginX,p.tz()-arOriginZ);modeText.text="● AR TRACKING • ${overlay.surveyCount()} RF POINTS";return}}catch(_:Exception){}};overlay.addSurveySample(r,stepCount,azimuth);modeText.text="● SENSOR TRACKING • ${overlay.surveyCount()} RF POINTS"}
 private fun updateLocator(r:Int){if(r>bestRssi)bestRssi=r;if(previousRssi<=-100){previousRssi=r;return};val d=r-previousRssi;directionArrow.text=if(d>=2)"↑" else if(d<=-2)"↶" else "↗";locateStatus.text="$r dBm • "+if(d>=2)"GETTING STRONGER" else if(d<=-2)"GETTING WEAKER" else "sampling…";previousRssi=r}
 override fun onSensorChanged(e:SensorEvent){when(e.sensor.type){Sensor.TYPE_STEP_COUNTER->{val raw=e.values[0].toInt();if(stepBase<0)stepBase=raw;stepCount=raw-stepBase};Sensor.TYPE_ROTATION_VECTOR->{val m=FloatArray(9);val o=FloatArray(3);SensorManager.getRotationMatrixFromVector(m,e.values);SensorManager.getOrientation(m,o);azimuth=o[0]}}};override fun onAccuracyChanged(s:Sensor?,a:Int){}
 override fun onResume(){super.onResume();stepSensor?.let{sensorManager.registerListener(this,it,SensorManager.SENSOR_DELAY_NORMAL)};rotationSensor?.let{sensorManager.registerListener(this,it,SensorManager.SENSOR_DELAY_GAME)}};override fun onPause(){sensorManager.unregisterListener(this);try{arSession?.pause()}catch(_:Exception){};super.onPause()};override fun onDestroy(){handler.removeCallbacks(poller);arSession?.close();super.onDestroy()}
}