package com.armanware.wifivision
import android.content.Context
import android.graphics.*
import android.util.AttributeSet
import android.view.View
import kotlin.math.*
class WifiOverlayView @JvmOverloads constructor(context:Context,attrs:AttributeSet?=null):View(context,attrs){
 enum class Mode{HOME,MAP};data class RfSample(val x:Float,val y:Float,val rssi:Int)
 var mode=Mode.HOME;set(v){field=v;invalidate()};private var rssi=-100;private val samples=ArrayList<RfSample>();private var px=0f;private var py=0f;private var lastStep=0
 private val paint=Paint(Paint.ANTI_ALIAS_FLAG);private val text=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.WHITE;textSize=44f;textAlign=Paint.Align.CENTER;isFakeBoldText=true}
 fun setRssi(v:Int){rssi=v.coerceIn(-100,-20);invalidate()};fun clearSurvey(){samples.clear();px=0f;py=0f;lastStep=0;invalidate()};fun surveyCount()=samples.size
 fun addSurveySample(v:Int,steps:Int,a:Float){if(samples.isEmpty()){samples.add(RfSample(0f,0f,v));lastStep=steps;invalidate();return};val ds=(steps-lastStep).coerceIn(0,4);if(ds>0){val m=ds*.72f;px+=(-sin(a)*m);py+=(-cos(a)*m);lastStep=steps;samples.add(RfSample(px,py,v));if(samples.size>1500)samples.removeAt(0);invalidate()}else if(abs(samples.last().rssi-v)>=4){samples.add(RfSample(px,py,v));invalidate()}}
 private fun color(v:Int)=when{v>=-45->Color.rgb(255,45,35);v>=-55->Color.rgb(255,170,0);v>=-65->Color.rgb(70,220,80);v>=-75->Color.CYAN;else->Color.rgb(40,70,255)}
 private fun ac(a:Int,b:Int)=Color.argb(a,Color.red(b),Color.green(b),Color.blue(b))
 override fun onDraw(c:Canvas){super.onDraw(c);if(mode==Mode.HOME)drawHome(c) else drawRobotMap(c)}
 private fun drawHome(c:Canvas){c.drawColor(Color.rgb(5,14,24));c.drawText("$rssi dBm",width/2f,height*.44f,text);val p=Paint(text).apply{textSize=25f;color=Color.rgb(90,180,255)};c.drawText("START SURVEY TO BUILD A WALKING RF MAP",width/2f,height*.51f,p)}
 private fun drawRobotMap(c:Canvas){c.drawColor(Color.rgb(4,12,20));paint.color=Color.rgb(18,35,48);paint.strokeWidth=2f;val grid=55f;var x=0f;while(x<width){c.drawLine(x,0f,x,height.toFloat(),paint);x+=grid};var y=0f;while(y<height){c.drawLine(0f,y,width.toFloat(),y,paint);y+=grid};if(samples.isEmpty()){c.drawText("PRESS SURVEY AND START WALKING",width/2f,height*.45f,Paint(text).apply{textSize=27f});return};val minX=samples.minOf{it.x};val maxX=samples.maxOf{it.x};val minY=samples.minOf{it.y};val maxY=samples.maxOf{it.y};val span=max(maxX-minX,maxY-minY).coerceAtLeast(4f);val scale=min(width*.78f,height*.68f)/span;val ox=width/2-(minX+maxX)/2*scale;val oy=height*.46f-(minY+maxY)/2*scale;val radius=(.9f*scale).coerceIn(55f,150f);samples.forEach{s->val sx=ox+s.x*scale;val sy=oy+s.y*scale;val col=color(s.rssi);paint.shader=RadialGradient(sx,sy,radius,intArrayOf(ac(190,col),ac(70,col),Color.TRANSPARENT),null,Shader.TileMode.CLAMP);c.drawCircle(sx,sy,radius,paint)};paint.shader=null;val path=Path();samples.forEachIndexed{i,s->val sx=ox+s.x*scale;val sy=oy+s.y*scale;if(i==0)path.moveTo(sx,sy)else path.lineTo(sx,sy)};paint.style=Paint.Style.STROKE;paint.strokeWidth=5f;paint.color=Color.argb(210,235,245,255);c.drawPath(path,paint);paint.style=Paint.Style.FILL;val start=samples.first();paint.color=Color.WHITE;c.drawCircle(ox+start.x*scale,oy+start.y*scale,12f,paint);val last=samples.last();val lx=ox+last.x*scale;val ly=oy+last.y*scale;paint.color=Color.rgb(50,180,255);c.drawCircle(lx,ly,18f,paint);paint.style=Paint.Style.STROKE;paint.strokeWidth=5f;paint.color=Color.WHITE;c.drawCircle(lx,ly,24f,paint);paint.style=Paint.Style.FILL;val best=samples.maxByOrNull{it.rssi}!!;paint.color=Color.rgb(255,215,0);c.drawCircle(ox+best.x*scale,oy+best.y*scale,11f,paint);val sm=Paint(text).apply{textSize=22f};c.drawText("START",ox+start.x*scale,oy+start.y*scale-25,sm);c.drawText("YOU",lx,ly-34,sm);sm.textSize=24f;c.drawText("${samples.size} points  •  strongest ${best.rssi} dBm",width/2f,height*.89f,sm);drawLegend(c)}
 private fun drawLegend(c:Canvas){val l=24f;val t=height*.63f;val h=height*.22f;paint.shader=LinearGradient(l,t,l,t+h,intArrayOf(Color.RED,Color.YELLOW,Color.GREEN,Color.CYAN,Color.BLUE),null,Shader.TileMode.CLAMP);c.drawRoundRect(l,t,l+28,t+h,12f,12f,paint);paint.shader=null;val p=Paint(text).apply{textAlign=Paint.Align.LEFT;textSize=18f};c.drawText("-30",60f,t+12,p);c.drawText("-60",60f,t+h/2,p);c.drawText("-90",60f,t+h,p)}
}