package com.armanware.wifivision
import android.content.Context
import android.graphics.*
import android.util.AttributeSet
import android.view.View
import kotlin.math.*
class WifiOverlayView @JvmOverloads constructor(context:Context,attrs:AttributeSet?=null):View(context,attrs){
 enum class Mode{AR,HEATMAP,PROPAGATION};data class RfSample(val x:Float,val y:Float,val rssi:Int)
 var mode=Mode.AR;set(v){field=v;invalidate()};private var rssi=-100;private val history=ArrayDeque<Int>();private val samples=ArrayList<RfSample>();private var px=0f;private var py=0f;private var lastStep=0
 private val paint=Paint(Paint.ANTI_ALIAS_FLAG);private val text=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.WHITE;textSize=52f;textAlign=Paint.Align.CENTER;isFakeBoldText=true}
 fun setRssi(v:Int,record:Boolean=false){rssi=v.coerceIn(-100,-20);if(record||mode!=Mode.AR){history.addLast(rssi);if(history.size>80)history.removeFirst()};invalidate()}
 fun clearSurvey(){samples.clear();px=0f;py=0f;lastStep=0;invalidate()};fun surveyCount()=samples.size
 fun addSpatialSample(v:Int,x:Float,z:Float){if(samples.isEmpty()||hypot(x-samples.last().x,z-samples.last().y)>.12f||abs(v-samples.last().rssi)>=2){samples.add(RfSample(x,z,v));if(samples.size>1000)samples.removeAt(0);invalidate()}}
 fun addSurveySample(v:Int,steps:Int,a:Float){if(samples.isEmpty()){samples.add(RfSample(0f,0f,v));lastStep=steps;return};val ds=(steps-lastStep).coerceIn(0,3);if(ds>0){val m=ds*.72f;px+=(-sin(a)*m);py+=(-cos(a)*m);lastStep=steps};if(ds>0||abs(samples.last().rssi-v)>=2){samples.add(RfSample(px,py,v));invalidate()}}
 private fun color(q:Float)=when{q>.8f->Color.RED;q>.62f->Color.YELLOW;q>.45f->Color.GREEN;q>.27f->Color.CYAN;else->Color.BLUE};private fun ac(a:Int,b:Int)=Color.argb(a,Color.red(b),Color.green(b),Color.blue(b))
 override fun onDraw(c:Canvas){super.onDraw(c);val q=((rssi+100)/80f).coerceIn(0f,1f);val cx=width/2f;val cy=height/2f;when(mode){Mode.AR->{val rad=min(width,height)*(.18f+q*.3f);paint.shader=RadialGradient(cx,cy,rad,intArrayOf(ac(210,color(q)),Color.argb(100,0,180,255),Color.TRANSPARENT),null,Shader.TileMode.CLAMP);c.drawCircle(cx,cy,rad,paint);paint.shader=null;c.drawText("$rssi dBm",cx,cy,text)};Mode.HEATMAP->drawHeat(c);Mode.PROPAGATION->drawMap(c)};drawLegend(c)}
 private fun drawHeat(c:Canvas){c.drawColor(Color.argb(110,0,0,15));if(history.isEmpty())history.add(rssi);history.forEachIndexed{i,v->val x=((i%6)+.5f)*width/6;val y=height-((i/6)+1)*height/15f;val q=((v+100)/80f).coerceIn(0f,1f);paint.shader=RadialGradient(x,y,width*.24f,intArrayOf(ac(210,color(q)),Color.TRANSPARENT),null,Shader.TileMode.CLAMP);c.drawCircle(x,y,width*.24f,paint)};paint.shader=null}
 private fun drawMap(c:Canvas){c.drawColor(Color.argb(205,0,5,15));if(samples.size<2){c.drawText("MOVE AROUND TO BUILD RF MAP",width/2f,height*.45f,Paint(text).apply{textSize=30f});return};val minX=samples.minOf{it.x};val maxX=samples.maxOf{it.x};val minY=samples.minOf{it.y};val maxY=samples.maxOf{it.y};val span=max(maxX-minX,maxY-minY).coerceAtLeast(1f);val scale=min(width*.76f,height*.65f)/span;val ox=width/2-(minX+maxX)/2*scale;val oy=height*.45f-(minY+maxY)/2*scale;samples.forEach{s->val x=ox+s.x*scale;val y=oy+s.y*scale;val q=((s.rssi+100)/80f).coerceIn(0f,1f);paint.shader=RadialGradient(x,y,120f,intArrayOf(ac(180,color(q)),ac(60,color(q)),Color.TRANSPARENT),null,Shader.TileMode.CLAMP);c.drawCircle(x,y,120f,paint)};paint.shader=null;paint.style=Paint.Style.STROKE;paint.strokeWidth=4f;paint.color=Color.WHITE;val p=Path();samples.forEachIndexed{i,s->val x=ox+s.x*scale;val y=oy+s.y*scale;if(i==0)p.moveTo(x,y)else p.lineTo(x,y)};c.drawPath(p,paint);paint.style=Paint.Style.FILL;val best=samples.maxByOrNull{it.rssi}!!;paint.color=Color.WHITE;c.drawCircle(ox+best.x*scale,oy+best.y*scale,15f,paint);val sm=Paint(text).apply{textSize=25f};c.drawText("Strongest measured area • ${best.rssi} dBm",width/2f,height*.84f,sm);sm.textSize=21f;c.drawText("${samples.size} spatial RF samples",width/2f,height*.89f,sm)}
 private fun drawLegend(c:Canvas){val l=24f;val t=height*.58f;val h=height*.28f;paint.shader=LinearGradient(l,t,l,t+h,intArrayOf(Color.RED,Color.YELLOW,Color.GREEN,Color.CYAN,Color.BLUE),null,Shader.TileMode.CLAMP);c.drawRect(l,t,l+30,t+h,paint);paint.shader=null}
}